### ISSUE TITLE
Not able to build Correct Environment app

### ISSUE THREAD

**Issue by buntsem** [therealemjy/react-native-tuto-multiple-environments#3]
When trying to build iOS app with either scheme it always builds the Development scheme

**Comment by buntsem** [comment]
running npx react-native run-ios, but Development app is installed instead of Production app.

**Comment by therealemjy** [comment]
Hmmm.. that's strange.
Have you tried running the app through Xcode directly?
You can select the development scheme via the top dropdown:

![Screen Shot 2021-03-18 at 10 41 44 AM](https://user-images.githubusercontent.com/44675210/111644976-b6873f00-87d6-11eb-8f2e-863243dcbe9d.png)


![Screen Shot 2021-03-18 at 10 41 58 AM](https://user-images.githubusercontent.com/44675210/111644984-b7b86c00-87d6-11eb-9f63-d016717ba6b3.png)

**Comment by buntsem** [comment]
Thanks for your quick reply, Yes I did, From both react-native command build and through the Xcode, correct app is installed on the simulator and device but the env.development data is presented in both cases(the value of ENVIRONMENT)

**Comment by buntsem** [comment]
On a new machine, where this project is not run before if the Production scheme is run first, it doesn't show data of Environment and then if we run the Development scheme and running back the production scheme it still shows the development scheme's data.

**Comment by therealemjy** [comment]
You're welcome.
There's a few possibilities I can think about:
- the wrong app is launched (this can happen when the wrong package is passed by React Native to launch the app), hence why you'd see the same data. That said, I trust you've checked which app is launched with what schemes
- there's an issue with caching. You could try to clear the cache and run the server again with this command:
```sh
react-native start --reset-cache
```
