### ISSUE TITLE
Multiple commands produce '.../Debug-iphonesimulator/OCR_POC.app/Info.plist'

### ISSUE THREAD

**Issue by patelhari** [therealemjy/react-native-tuto-multiple-environments#5]
Multiple commands produce '.../Debug-iphonesimulator/OCR_POC.app/Info.plist':
1) Target 'OCR_POC' (project 'OCR_POC') has copy command from '.../OCRPOCDevelopment/Info.plist' to '.../OCR_POC.app/Info.plist'
2) Target 'OCR_POC' (project 'OCR_POC') has process command with output '.../OCR_POC.app/Info.plist'

**Comment by therealemjy** [comment]
hmmm... I'm gonna need a bit more details here 😬
What exact command is producing this error?

if you can provide a minimal reproduction of the error I can have a look for you.

**Comment by patelhari** [comment]
https://medium.com/swlh/setting-up-multiple-environments-on-react-native-for-ios-and-android-c43f3128754f

I follow the steps from this link and try to build / run getting this error. even i download this project and build / run example of this project also getting same error.

Thank you
